# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
script:
  - python setup.py develop
  - python tests/
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
